version: "3.7"

volumes:
  app-volume:
  mysql-data:

services:
  app:
#    build:
#      context: .
#      dockerfile: Dockerfile
    image: "${APP_IMAGE}"
    container_name: "${PROJECT_NAME}-app"
    restart: unless-stopped
    volumes:
      - app-volume:/var/www
      - ./laravel/logs:/var/www/storage/logs
      - .env.laravel:/var/www/.env
    links:
      - mysql

  supervisor:
    image: "${APP_IMAGE}"
    container_name: "${PROJECT_NAME}-supervisor"
    user: root
    volumes:
      - app-volume:/var/www
      - ./laravel/logs:/var/www/storage/logs
      - .env.laravel:/var/www/.env
    entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
    links:
      - app

  mysql:
    image: mysql:latest
    container_name: "${PROJECT_NAME}-mysql"
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - mysql-data:/var/lib/mysql/

  nginx:
    image: nginx:latest
    container_name: "${PROJECT_NAME}-nginx"
    restart: unless-stopped
    volumes:
      - app-volume:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx/
    environment:
      - PROJECT_URL
      - PROJECT_ROOT
      - VIRTUAL_HOST
      - VIRTUAL_PORT
    expose:
      - $VIRTUAL_PORT
    ports:
      - $VIRTUAL_PORT:$VIRTUAL_PORT
    command: /bin/bash -c "envsubst < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/my.conf && nginx -g 'daemon off;'"
    links:
      - app
